In [27]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import cross_val_predict, cross_validate
from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('../data/raw/admission.csv')

In [16]:
df.sample(10)

,Unnamed: 0,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
168,168,169,293,97,2,2.0,4.0,7.80,1,0.64
112,112,113,301,107,3,3.5,3.5,8.34,1,0.62
355,355,356,317,106,2,2.0,3.5,8.12,0,0.73
312,312,313,311,107,4,4.5,4.5,9.00,1,0.78
71,71,72,336,112,5,5.0,5.0,9.76,1,0.96
234,234,235,330,113,5,5.0,4.0,9.31,1,0.91
95,95,96,304,100,4,1.5,2.5,7.84,0,0.42
172,172,173,322,110,4,4.0,5.0,9.13,1,0.86
126,126,127,323,113,3,4.0,3.0,9.32,1,0.85
263,263,264,324,111,3,2.5,1.5,8.79,1,0.70

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         500 non-null    int64
 1   Serial No.         500 non-null    int64
 2   GRE Score          500 non-null    int64
 3   TOEFL Score        500 non-null    int64
 4   University Rating  500 non-null    int64
 5   SOP                500 non-null    float64
 6   LOR                500 non-null    float64
 7   CGPA               500 non-null    float64
 8   Research           500 non-null    int64
 9   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(6)
memory usage: 39.2 KB

In [26]:
df.describe()

,Unnamed: 0,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000,500.00000
mean,249.500000,250.500000,316.472000,107.192000,3.114000,3.374000,3.48400,8.576440,0.560000,0.72174
std,144.481833,144.481833,11.295148,6.081868,1.143512,0.991004,0.92545,0.604813,0.496884,0.14114
min,0.000000,1.000000,290.000000,92.000000,1.000000,1.000000,1.00000,6.800000,0.000000,0.34000
25%,124.750000,125.750000,308.000000,103.000000,2.000000,2.500000,3.00000,8.127500,0.000000,0.63000
50%,249.500000,250.500000,317.000000,107.000000,3.000000,3.500000,3.50000,8.560000,1.000000,0.72000
75%,374.250000,375.250000,325.000000,112.000000,4.000000,4.000000,4.00000,9.040000,1.000000,0.82000
max,499.000000,500.000000,340.000000,120.000000,5.000000,5.000000,5.00000,9.920000,1.000000,0.97000

In [18]:
df.columns.to_list()

['Unnamed: 0',
 'Serial No.',
 'GRE Score',
 'TOEFL Score',
 'University Rating',
 'SOP',
 'LOR ',
 'CGPA',
 'Research',
 'Chance of Admit ']

In [21]:
df.columns.to_list()

['Unnamed: 0',
 'Serial No.',
 'GRE Score',
 'TOEFL Score',
 'University Rating',
 'SOP',
 'LOR ',
 'CGPA',
 'Research',
 'Chance of Admit ']

In [25]:
cols_X = df.columns.drop(['Chance of Admit ','Unnamed: 0'])
col_y = ['Chance of Admit ']
cols_X

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research'],
      dtype='object')